modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="border_weaver"
version="1.0.0"
displayName="Border Weaver"
authors="Alku"
description='''
A mod to weave world borders.
'''

[[dependencies.border_weaver]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.border_weaver]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"