modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="life_contract"
version="1.0.0"
displayName="Life Contract"
description="Connects your soul to other mods."
authors="Alku"

[[dependencies.life_contract]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.life_contract]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"